version: "3"

networks:
  web:
    external: true
  internal:
    external: false

services:
  db:
    container_name: postgresdb
    image: postgres
    restart: always
    env_file:
      - .env
    networks:
      - internal
    volumes:
      - postgres-data:/var/lib/postgresql/data

  school_document:
    container_name: django
    build: .    
    command: gunicorn school_document.wsgi:application --access-logfile /code/log.log --error-logfile /code/error.log --capture-output --enable-stdio-inheritance --bind 0.0.0.0:8000 --workers=4
    expose:
      - 8000
    env_file:
      - .env
    networks:
      - internal
    volumes:
      - static-files:/code/static
      - media-files:/code/media
    depends_on:
      - db

  nginx:
    image: nginx:1.15-alpine
    networks:
      - internal
      - web
    volumes:
      - static-files:/code/static
      - media-files:/code/media
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/conf:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
    depends_on:
      - school_document
  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot

volumes:
  postgres-data:
  static-files:
  media-files:
