version: "3"

networks:
  internal:
    external: false
  web:
    external: true

services:
  db:
    container_name: postgresdb
    image: postgres
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - internal
    volumes:
      - postgres-data:/var/lib/postgresql/data

  school_document:
    container_name: django
    restart: unless-stopped
    build: .    
    command: gunicorn school_document.wsgi:application --access-logfile /code/log.log --error-logfile /code/error.log --capture-output --enable-stdio-inheritance --bind 0.0.0.0:8000 --workers=4
    expose:
      - 8000
    env_file:
      - .env
    networks:
      - internal
      - web
    volumes:
      - static-files:/code/static
      - media-files:/code/media
    depends_on:
      - db

volumes:
  postgres-data:
  static-files:
  media-files:
