# Generated by Django 2.2.5 on 2020-02-15 20:04

import back.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('type_num', models.CharField(choices=[('Семинары', 'seminars'), ('Семистровки', 'semistrovki')], max_length=50)),
                ('class_num', models.CharField(choices=[('10А', '10А'), ('10Б', '10Б'), ('10В', '10В'), ('11А', '11А'), ('11Б', '11Б'), ('11В', '11В')], max_length=50)),
                ('post_date', models.DateField(auto_now=True)),
                ('image', models.ImageField(upload_to=back.models.get_img_path)),
            ],
        ),
    ]
