# Generated by Django 2.2.5 on 2020-02-15 20:54

import back.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(null=True, upload_to=back.models.get_img_path),
        ),
    ]
