# Generated by Django 2.2.5 on 2020-02-15 20:55

import back.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_auto_20200216_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(upload_to=back.models.get_img_path),
        ),
    ]
