# Generated by Django 2.2.5 on 2020-02-17 17:00

import back.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_card_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=back.models.get_img_path),
        ),
    ]
