# Generated by Django 2.2.5 on 2020-02-17 17:37

import back.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0006_auto_20200217_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=back.models.get_img_path)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='back.Card')),
            ],
        ),
        migrations.DeleteModel(
            name='Imgae',
        ),
    ]
