# Generated by Django 2.2.5 on 2020-02-17 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0007_auto_20200217_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='post',
            new_name='card',
        ),
    ]
