# Generated by Django 2.2.5 on 2020-02-17 18:04

import back.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0008_auto_20200217_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=back.models.get_img_path),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
