# Generated by Django 2.2.5 on 2020-02-23 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0012_auto_20200221_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='class_num',
            new_name='group_num',
        ),
    ]
