# Generated by Django 2.2.5 on 2020-02-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0013_auto_20200223_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='teacher',
            field=models.CharField(choices=[('Попов Д.А', 'Попов Д.А'), ('Ильин А.Б', 'Ильин А.Б'), ('Пачин И.М', 'Пачин И.М')], default=('Попов Д.А', 'Попов Д.А'), max_length=100),
        ),
    ]
