# Generated by Django 2.2.5 on 2020-02-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0014_auto_20200223_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='id',
        ),
        migrations.AddField(
            model_name='card',
            name='card_id',
            field=models.AutoField(default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
