# Generated by Django 2.2.5 on 2020-02-24 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0015_auto_20200224_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='slug',
        ),
    ]
