# Generated by Django 2.2.5 on 2020-02-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0016_remove_card_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='teacher',
            field=models.CharField(choices=[('Попов Д.А', 'Попов Д.А'), ('Ильин А.Б', 'Ильин А.Б'), ('Пачин И.М', 'Пачин И.М'), ('Николаева Л.Н', 'Николаева Л.Н')], default=('Попов Д.А', 'Попов Д.А'), max_length=100),
        ),
    ]
