# Generated by Django 2.2.5 on 2020-02-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0017_auto_20200224_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
