# Generated by Django 2.2.5 on 2020-02-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0018_auto_20200226_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='teacher',
            field=models.CharField(choices=[('Попов Д.А', 'Попов Д.А'), ('Ильин А.Б', 'Ильин А.Б'), ('Пачин И.М', 'Пачин И.М'), ('Николаева Л.Н', 'Николаева Л.Н'), ('Ню В.В', 'Ню В.В'), ('Вишневская Е.А', 'Вишневская Е.А'), ('Некрасов М.В', 'Некрасов М.В'), ('Попова Н.А', 'Попова Н.А'), ('Пачин М.Ф', 'Пачин М.Ф'), ('Керамов Н.Д', 'Керамов Н.Д'), ('Новожилова В.И', 'Новожилова В.И'), ('Шпехт А.Ю', 'Шпехт А.Ю'), ('Конкина Н.В', 'Конкина Н.В')], default=('Попов Д.А', 'Попов Д.А'), max_length=100),
        ),
    ]
