# Generated by Django 2.2.5 on 2020-02-27 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0021_auto_20200227_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='poster',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
