# Generated by Django 2.2.5 on 2020-03-01 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0024_auto_20200227_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='poster',
            new_name='user',
        ),
    ]
