# Generated by Django 2.2.5 on 2020-03-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0025_auto_20200301_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='predmet_type',
            field=models.CharField(choices=[('Математика', 'Математика'), ('Физика', 'Физика'), ('Информатика', 'Информатика')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='group_num',
            field=models.CharField(choices=[('10', '10'), ('11', '11')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='teacher',
            field=models.CharField(choices=[('Попов Д.А', 'Попов Д.А'), ('Ильин А.Б', 'Ильин А.Б'), ('Пачин И.М', 'Пачин И.М'), ('Николаева Л.Н', 'Николаева Л.Н'), ('Ню В.В', 'Ню В.В'), ('Вишневская Е.А', 'Вишневская Е.А'), ('Некрасов М.В', 'Некрасов М.В'), ('Попова Н.А', 'Попова Н.А'), ('Пачин М.Ф', 'Пачин М.Ф'), ('Керамов Н.Д', 'Керамов Н.Д'), ('Новожилова В.И', 'Новожилова В.И'), ('Шпехт А.Ю', 'Шпехт А.Ю'), ('Конкина Н.В', 'Конкина Н.В')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='type_num',
            field=models.CharField(choices=[('Семинары', 'seminars'), ('Семестровки', 'semestrovki'), ('Потоковые', 'potocovye')], max_length=50, null=True),
        ),
    ]
